// Generated by CoffeeScript 1.12.5
(function() {
  var parseJSON, to_campfire, to_vignete;

  (function($) {})(jQuery);

  window.App = {};

  App.parseJSON = parseJSON = function(data) {
    return console.log(data);
  };

  window.onload = function() {
    console.log('window is loaded, populating campfire...');
    App.campfire = {};
    App.campfire.scene = $('#Campfire');
    return $.getJSON('src/json/campfire.json', App.parseJSON);
  };

  App.to_vignette = to_vignete = function(vignette) {
    return console.log("going to vignette " + vignette);
  };

  App.to_campfire = to_campfire = function() {
    return console.log("returning to campfire");
  };

}).call(this);
